package com.jarvys.agent;

import android.content.Context;

import java.io.File;
import java.io.FileOutputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Locale;

/** Private per-conversation generated images; paths stored in JSONL are session-relative filenames. */
public final class GeneratedImageStore {
    private static final String SESSION_PATTERN = "[A-Za-z0-9_.-]{1,100}";
    private static final String IMAGE_PATTERN = "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\\.png";
    private final File generatedRoot;
    private final String canonicalRoot;

    public GeneratedImageStore(Context context) {
        this(new File(context.getApplicationContext().getFilesDir(), "jarvys"));
    }

    /** Package constructor accepts the private filesDir/jarvys root for local tests. */
    GeneratedImageStore(File jarvysRoot) {
        File absoluteJarvysRoot = jarvysRoot.getAbsoluteFile();
        File parent = absoluteJarvysRoot.getParentFile();
        if (parent == null) throw new IllegalArgumentException("Generated image root must have a parent directory");
        generatedRoot = new File(absoluteJarvysRoot, "generated");
        canonicalRoot = canonical(generatedRoot);
        String expectedRoot = new File(new File(canonical(parent), absoluteJarvysRoot.getName()), "generated").getPath();
        if (!canonicalRoot.equals(expectedRoot)) {
            throw new IllegalArgumentException("Generated image root cannot be a symbolic link");
        }
    }

    public String save(String sessionId, String imageId, byte[] pngBytes) {
        validateSession(sessionId);
        if (imageId == null || !imageId.matches("[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")) {
            throw new IllegalArgumentException("Generated image id is invalid");
        }
        if (!hasPngSignature(pngBytes)) throw new IllegalArgumentException("Generated bytes are not a PNG image");
        File directory = sessionDirectory(sessionId);
        if (!directory.isDirectory() && !directory.mkdirs()) throw new IllegalStateException("Could not create private image storage");
        rejectSymlink(directory);
        File target = new File(directory, imageId + ".png");
        File temporary = null;
        try {
            temporary = File.createTempFile(".image-", ".tmp", directory);
            try (FileOutputStream output = new FileOutputStream(temporary, false)) {
                output.write(pngBytes);
                output.flush();
                output.getFD().sync();
            }
            if (!temporary.renameTo(target)) throw new IllegalStateException("Could not atomically save generated image");
            return target.getName();
        } catch (RuntimeException error) {
            throw error;
        } catch (Exception error) {
            throw new IllegalStateException("Could not save generated image", error);
        } finally {
            if (temporary != null && temporary.exists()) temporary.delete();
        }
    }

    public File resolve(String sessionId, String relativePath) {
        validateSession(sessionId);
        if (relativePath == null || !relativePath.matches(IMAGE_PATTERN)) {
            throw new IllegalArgumentException("Generated image path is invalid");
        }
        File session = sessionDirectory(sessionId);
        File target = new File(session, relativePath);
        String canonical = canonical(target);
        if (!canonical.startsWith(canonicalRoot + File.separator) || !canonical.startsWith(canonical(session) + File.separator)) {
            throw new IllegalArgumentException("Generated image path escapes private storage");
        }
        if (!target.isFile()) throw new IllegalArgumentException("Generated image file is missing");
        rejectSymlink(target);
        return target;
    }

    public File sessionDirectory(String sessionId) {
        validateSession(sessionId);
        rejectGeneratedRootSymlink();
        File directory = new File(generatedRoot, sessionId);
        if (directory.exists()) rejectSymlink(directory);
        String canonical = canonical(directory);
        if (!canonical.startsWith(canonicalRoot + File.separator)) {
            throw new IllegalArgumentException("Conversation image path escapes private storage");
        }
        return directory;
    }

    public boolean isGeneratedFile(File file) {
        if (file == null || !file.isFile()) return false;
        rejectGeneratedRootSymlink();
        if (expectedCanonicalPath(file) == null) return false;
        rejectSymlink(file);
        String canonical = canonical(file);
        return canonical.startsWith(canonicalRoot + File.separator);
    }

    public boolean deleteSession(String sessionId) {
        File directory = sessionDirectory(sessionId);
        if (!directory.exists()) return true;
        deleteTree(directory);
        return !directory.exists();
    }

    public boolean deleteImage(String sessionId, String relativePath) {
        File image = resolve(sessionId, relativePath);
        return !image.exists() || image.delete();
    }

    public File rootDirectory() { return generatedRoot; }

    private void rejectGeneratedRootSymlink() {
        if (!canonical(generatedRoot).equals(canonicalRoot)) {
            throw new IllegalArgumentException("Generated image root cannot be a symbolic link");
        }
    }

    private void deleteTree(File file) {
        rejectSymlink(file);
        if (file.isDirectory()) {
            File[] children = file.listFiles();
            if (children != null) for (File child : children) deleteTree(child);
        }
        if (file.exists() && !file.delete()) throw new IllegalStateException("Could not remove generated image data");
    }

    private static boolean hasPngSignature(byte[] bytes) {
        byte[] signature = new byte[]{(byte) 0x89, 'P', 'N', 'G', 13, 10, 26, 10};
        if (bytes == null || bytes.length < signature.length) return false;
        for (int index = 0; index < signature.length; index++) if (bytes[index] != signature[index]) return false;
        return true;
    }

    private static void validateSession(String sessionId) {
        if (sessionId == null || !sessionId.matches(SESSION_PATTERN) || sessionId.equals(".") || sessionId.equals("..")) {
            throw new IllegalArgumentException("Conversation session id is invalid for image storage");
        }
    }

    private void rejectSymlink(File file) {
        try {
            String expected = expectedCanonicalPath(file);
            if (expected == null || !file.getCanonicalPath().equals(expected)) {
                throw new IllegalArgumentException("Generated image paths cannot use symbolic links");
            }
        } catch (IllegalArgumentException error) {
            throw error;
        } catch (Exception error) {
            throw new IllegalArgumentException("Could not resolve generated image path", error);
        }
    }

    private String expectedCanonicalPath(File file) {
        String rootPath = generatedRoot.getAbsolutePath();
        String filePath = file.getAbsolutePath();
        if (filePath.equals(rootPath)) return canonicalRoot;
        if (!filePath.startsWith(rootPath + File.separator)) return null;
        String relative = filePath.substring(rootPath.length() + 1);
        return new File(canonicalRoot, relative).getPath();
    }

    private static String canonical(File file) {
        try { return file.getCanonicalPath(); }
        catch (Exception error) { throw new IllegalStateException("Could not resolve private image storage", error); }
    }
}
