package com.jarvys.agent

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

/** ImageVectors generated from Lucide 0.575.0 official SVGs; generated by the one-shot offline script. */
internal object LucideIcons {
    private fun vector(name: String, d: String): ImageVector = ImageVector.Builder(
        name = name, defaultWidth = 24.dp, defaultHeight = 24.dp, viewportWidth = 24f, viewportHeight = 24f,
    ).apply {
        addPath(
            pathData = PathParser().parsePathString(d).toNodes(),
            fill = SolidColor(Color.Transparent), stroke = SolidColor(Color.Black), strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round, strokeLineJoin = StrokeJoin.Round,
        )
    }.build()

    val Accessibility: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Accessibility", "M 17 4 A 1 1 0 1 0 15 4 A 1 1 0 1 0 17 4 M 0 0 m18 19 1-7-6 1 M 0 0 m5 8 3-3 5.5 3-2.36 3.5 M 0 0 M4.24 14.5a5 5 0 0 0 6.88 6 M 0 0 M13.76 17.5a5 5 0 0 0-6.88-6") }
    val Plus: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Plus", "M5 12h14 M 0 0 M12 5v14") }
    val Mic: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Mic", "M12 19v3 M 0 0 M19 10v2a7 7 0 0 1-14 0v-2 M 0 0 M12 2 A3 3 0 0 1 15 5 V12 A3 3 0 0 1 9 12 V5 A3 3 0 0 1 12 2 Z") }
    val MessageCirclePlus: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("MessageCirclePlus", "M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719 M 0 0 M8 12h8 M 0 0 M12 8v8") }
    val Boxes: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Boxes", "M2.97 12.92A2 2 0 0 0 2 14.63v3.24a2 2 0 0 0 .97 1.71l3 1.8a2 2 0 0 0 2.06 0L12 19v-5.5l-5-3-4.03 2.42Z M 0 0 m7 16.5-4.74-2.85 M 0 0 m7 16.5 5-3 M 0 0 M7 16.5v5.17 M 0 0 M12 13.5V19l3.97 2.38a2 2 0 0 0 2.06 0l3-1.8a2 2 0 0 0 .97-1.71v-3.24a2 2 0 0 0-.97-1.71L17 10.5l-5 3Z M 0 0 m17 16.5-5-3 M 0 0 m17 16.5 4.74-2.85 M 0 0 M17 16.5v5.17 M 0 0 M7.97 4.42A2 2 0 0 0 7 6.13v4.37l5 3 5-3V6.13a2 2 0 0 0-.97-1.71l-3-1.8a2 2 0 0 0-2.06 0l-3 1.8Z M 0 0 M12 8 7.26 5.15 M 0 0 m12 8 4.74-2.85 M 0 0 M12 13.5V8") }
    val ArrowLeft: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("ArrowLeft", "m12 19-7-7 7-7 M 0 0 M19 12H5") }
    val ArrowUp: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("ArrowUp", "m5 12 7-7 7 7 M 0 0 M12 19V5") }
    val Paperclip: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Paperclip", "m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551") }
    val Sparkles: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Sparkles", "M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z M 0 0 M20 2v4 M 0 0 M22 4h-4 M 0 0 M 6 20 A 2 2 0 1 0 2 20 A 2 2 0 1 0 6 20") }
    val SunMoon: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("SunMoon", "M12 2v2 M 0 0 M14.837 16.385a6 6 0 1 1-7.223-7.222c.624-.147.97.66.715 1.248a4 4 0 0 0 5.26 5.259c.589-.255 1.396.09 1.248.715 M 0 0 M16 12a4 4 0 0 0-4-4 M 0 0 m19 5-1.256 1.256 M 0 0 M20 12h2") }
    val Calendar: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Calendar", "M8 2v4 M 0 0 M16 2v4 M 0 0 M 5 4 H 19 A 2 2 0 0 1 21 6 V 20 A 2 2 0 0 1 19 22 H 5 A 2 2 0 0 1 3 20 V 6 A 2 2 0 0 1 5 4 Z M 0 0 M3 10h18") }
    val Smartphone: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Smartphone", "M 7 2 H 17 A 2 2 0 0 1 19 4 V 20 A 2 2 0 0 1 17 22 H 7 A 2 2 0 0 1 5 20 V 4 A 2 2 0 0 1 7 2 Z M 0 0 M12 18h.01") }
    val Camera: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Camera", "M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z M 0 0 M 15 13 A 3 3 0 1 0 9 13 A 3 3 0 1 0 15 13") }
    val CircleX: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("CircleX", "M 22 12 A 10 10 0 1 0 2 12 A 10 10 0 1 0 22 12 M 0 0 m15 9-6 6 M 0 0 m9 9 6 6") }
    val CircleCheck: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("CircleCheck", "M 22 12 A 10 10 0 1 0 2 12 A 10 10 0 1 0 22 12 M 0 0 m9 12 2 2 4-4") }
    val ContactRound: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("ContactRound", "M16 2v2 M 0 0 M17.915 22a6 6 0 0 0-12 0 M 0 0 M8 2v2 M 0 0 M 16 12 A 4 4 0 1 0 8 12 A 4 4 0 1 0 16 12 M 0 0 M 5 4 H 19 A 2 2 0 0 1 21 6 V 20 A 2 2 0 0 1 19 22 H 5 A 2 2 0 0 1 3 20 V 6 A 2 2 0 0 1 5 4 Z") }
    val Trash2: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Trash2", "M10 11v6 M 0 0 M14 11v6 M 0 0 M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6 M 0 0 M3 6h18 M 0 0 M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2") }
    val Download: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Download", "M12 15V3 M 0 0 M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4 M 0 0 m7 10 5 5 5-5") }
    val Heart: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Heart", "M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5") }
    val History: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("History", "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8 M 0 0 M3 3v5h5 M 0 0 M12 7v5l4 2") }
    val House: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("House", "M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8 M 0 0 M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z") }
    val Image: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Image", "M 5 3 H 19 A 2 2 0 0 1 21 5 V 19 A 2 2 0 0 1 19 21 H 5 A 2 2 0 0 1 3 19 V 5 A 2 2 0 0 1 5 3 Z M 0 0 M 11 9 A 2 2 0 1 0 7 9 A 2 2 0 1 0 11 9 M 0 0 m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21") }
    val Info: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Info", "M 22 12 A 10 10 0 1 0 2 12 A 10 10 0 1 0 22 12 M 0 0 M12 16v-4 M 0 0 M12 8h.01") }
    val ChevronDown: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("ChevronDown", "m6 9 6 6 6-6") }
    val ChevronRight: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("ChevronRight", "m9 18 6-6-6-6") }
    val ChevronUp: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("ChevronUp", "m18 15-6-6-6 6") }
    val Layers2: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Layers2", "M13 13.74a2 2 0 0 1-2 0L2.5 8.87a1 1 0 0 1 0-1.74L11 2.26a2 2 0 0 1 2 0l8.5 4.87a1 1 0 0 1 0 1.74z M 0 0 m20 14.285 1.5.845a1 1 0 0 1 0 1.74L13 21.74a2 2 0 0 1-2 0l-8.5-4.87a1 1 0 0 1 0-1.74l1.5-.845") }
    val MapPin: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("MapPin", "M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0 M 0 0 M 15 10 A 3 3 0 1 0 9 10 A 3 3 0 1 0 15 10") }
    val Brain: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Brain", "M12 18V5 M 0 0 M15 13a4.17 4.17 0 0 1-3-4 4.17 4.17 0 0 1-3 4 M 0 0 M17.598 6.5A3 3 0 1 0 12 5a3 3 0 1 0-5.598 1.5 M 0 0 M17.997 5.125a4 4 0 0 1 2.526 5.77 M 0 0 M18 18a4 4 0 0 0 2-7.464 M 0 0 M19.967 17.483A4 4 0 1 1 12 18a4 4 0 1 1-7.967-.517 M 0 0 M6 18a4 4 0 0 1-2-7.464 M 0 0 M6.003 5.125a4 4 0 0 0-2.526 5.77") }
    val Menu: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Menu", "M4 5h16 M 0 0 M4 12h16 M 0 0 M4 19h16") }
    val Bell: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Bell", "M10.268 21a2 2 0 0 0 3.464 0 M 0 0 M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326") }
    val Globe: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Globe", "M21.54 15H17a2 2 0 0 0-2 2v4.54 M 0 0 M7 3.34V5a3 3 0 0 0 3 3a2 2 0 0 1 2 2c0 1.1.9 2 2 2a2 2 0 0 0 2-2c0-1.1.9-2 2-2h3.17 M 0 0 M11 21.95V18a2 2 0 0 0-2-2a2 2 0 0 1-2-2v-1a2 2 0 0 0-2-2H2.05 M 0 0 M 22 12 A 10 10 0 1 0 2 12 A 10 10 0 1 0 22 12") }
    val Circle: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Circle", "M 22 12 A 10 10 0 1 0 2 12 A 10 10 0 1 0 22 12") }
    val RotateCcw: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("RotateCcw", "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8 M 0 0 M3 3v5h5") }
    val Save: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Save", "M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z M 0 0 M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7 M 0 0 M7 3v4a1 1 0 0 0 1 1h7") }
    val Clock: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Clock", "M 22 12 A 10 10 0 1 0 2 12 A 10 10 0 1 0 22 12 M 0 0 M12 6v6l4 2") }
    val Search: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Search", "m21 21-4.34-4.34 M 0 0 M 19 11 A 8 8 0 1 0 3 11 A 8 8 0 1 0 19 11") }
    val Shield: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Shield", "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z") }
    val Settings: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Settings", "M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915 M 0 0 M 15 12 A 3 3 0 1 0 9 12 A 3 3 0 1 0 15 12") }
    val MessageSquare: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("MessageSquare", "M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z") }
    val CircleStop: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("CircleStop", "M 22 12 A 10 10 0 1 0 2 12 A 10 10 0 1 0 22 12 M 0 0 M 10 9 H 14 A 1 1 0 0 1 15 10 V 14 A 1 1 0 0 1 14 15 H 10 A 1 1 0 0 1 9 14 V 10 A 1 1 0 0 1 10 9 Z") }
    val Bot: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Bot", "M12 8V4H8 M 0 0 M 6 8 H 18 A 2 2 0 0 1 20 10 V 18 A 2 2 0 0 1 18 20 H 6 A 2 2 0 0 1 4 18 V 10 A 2 2 0 0 1 6 8 Z M 0 0 M2 14h2 M 0 0 M20 14h2 M 0 0 M15 13v2 M 0 0 M9 13v2") }
    val Eye: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Eye", "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0 M 0 0 M 15 12 A 3 3 0 1 0 9 12 A 3 3 0 1 0 15 12") }
    val WandSparkles: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("WandSparkles", "m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72 M 0 0 m14 7 3 3 M 0 0 M5 6v4 M 0 0 M19 14v4 M 0 0 M10 2v2 M 0 0 M7 8H3 M 0 0 M21 16h-4 M 0 0 M11 3H9") }
    val Terminal: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Terminal", "M12 19h8 M 0 0 m4 17 6-6-6-6") }
    val FileText: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("FileText", "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z M 0 0 M14 2v5a1 1 0 0 0 1 1h5 M 0 0 M10 9H8 M 0 0 M16 13H8 M 0 0 M16 17H8") }
    val Network: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Network", "M 17 16 H 21 A 1 1 0 0 1 22 17 V 21 A 1 1 0 0 1 21 22 H 17 A 1 1 0 0 1 16 21 V 17 A 1 1 0 0 1 17 16 Z M 0 0 M 3 16 H 7 A 1 1 0 0 1 8 17 V 21 A 1 1 0 0 1 7 22 H 3 A 1 1 0 0 1 2 21 V 17 A 1 1 0 0 1 3 16 Z M 0 0 M 10 2 H 14 A 1 1 0 0 1 15 3 V 7 A 1 1 0 0 1 14 8 H 10 A 1 1 0 0 1 9 7 V 3 A 1 1 0 0 1 10 2 Z M 0 0 M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3 M 0 0 M12 12V8") }
    val Copy: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Copy", "M 10 8 H 20 A 2 2 0 0 1 22 10 V 20 A 2 2 0 0 1 20 22 H 10 A 2 2 0 0 1 8 20 V 10 A 2 2 0 0 1 10 8 Z M 0 0 M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2") }
    val RefreshCw: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("RefreshCw", "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8 M 0 0 M21 3v5h-5 M 0 0 M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16 M 0 0 M8 16H3v5") }
    val Volume2: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Volume2", "M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z M 0 0 M16 9a5 5 0 0 1 0 6 M 0 0 M19.364 18.364a9 9 0 0 0 0-12.728") }
    val Languages: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Languages", "m5 8 6 6 M 0 0 m4 14 6-6 2-3 M 0 0 M2 5h12 M 0 0 M7 2h1 M 0 0 m22 22-5-10-5 10 M 0 0 M14 18h6") }
    val Ellipsis: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("Ellipsis", "M 13 12 A 1 1 0 1 0 11 12 A 1 1 0 1 0 13 12 M 0 0 M 20 12 A 1 1 0 1 0 18 12 A 1 1 0 1 0 20 12 M 0 0 M 6 12 A 1 1 0 1 0 4 12 A 1 1 0 1 0 6 12") }
    val X: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("X", "M18 6 6 18 M 0 0 m6 6 12 12") }
    val ClipboardPaste: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("ClipboardPaste", "M11 14h10 M 0 0 M16 4h2a2 2 0 0 1 2 2v1.344 M 0 0 m17 18 4-4-4-4 M 0 0 M8 4H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 1.793-1.113 M 0 0 M 9 2 H 15 A 1 1 0 0 1 16 3 V 5 A 1 1 0 0 1 15 6 H 9 A 1 1 0 0 1 8 5 V 3 A 1 1 0 0 1 9 2 Z") }
    val FileUp: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("FileUp", "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z M 0 0 M14 2v5a1 1 0 0 0 1 1h5 M 0 0 M12 12v6 M 0 0 m15 15-3-3-3 3") }
    val GitFork: ImageVector by lazy(LazyThreadSafetyMode.PUBLICATION) { vector("GitFork", "M 15 18 A 3 3 0 1 0 9 18 A 3 3 0 1 0 15 18 M 0 0 M 9 6 A 3 3 0 1 0 3 6 A 3 3 0 1 0 9 6 M 0 0 M 21 6 A 3 3 0 1 0 15 6 A 3 3 0 1 0 21 6 M 0 0 M18 9v2c0 .6-.4 1-1 1H7c-.6 0-1-.4-1-1V9 M 0 0 M12 12v3") }

    fun all(): List<ImageVector> = listOf(
        Accessibility,
        Plus,
        Mic,
        MessageCirclePlus,
        Boxes,
        ArrowLeft,
        ArrowUp,
        Paperclip,
        Sparkles,
        SunMoon,
        Calendar,
        Smartphone,
        Camera,
        CircleX,
        CircleCheck,
        ContactRound,
        Trash2,
        Download,
        Heart,
        History,
        House,
        Image,
        Info,
        ChevronDown,
        ChevronRight,
        ChevronUp,
        Layers2,
        MapPin,
        Brain,
        Menu,
        Bell,
        Globe,
        Circle,
        RotateCcw,
        Save,
        Clock,
        Search,
        Shield,
        Settings,
        MessageSquare,
        CircleStop,
        Bot,
        Eye,
        WandSparkles,
        Terminal,
        FileText,
        Network,
        Copy,
        RefreshCw,
        Volume2,
        Languages,
        Ellipsis,
        X,
        ClipboardPaste,
        FileUp,
        GitFork,
    )
}
